/*
 * generated by Xtext 2.20.0
 */
package org.xtext.cs130.statemachine;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StateMachineStandaloneSetup extends StateMachineStandaloneSetupGenerated {

	public static void doSetup() {
		new StateMachineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
