/*
 * generated by Xtext 2.20.0
 */
package org.xtext.cs130.statemachine.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateMachineScopeProvider extends DelegatingScopeProvider {
}
