/**
 * generated by Xtext 2.20.0
 */
package org.xtext.cs130.statemachine.stateMachine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getVardefs <em>Vardefs</em>}</li>
 *   <li>{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getEventdefs <em>Eventdefs</em>}</li>
 *   <li>{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getStatedefs <em>Statedefs</em>}</li>
 * </ul>
 *
 * @see org.xtext.cs130.statemachine.stateMachine.StateMachinePackage#getStateMachine()
 * @model
 * @generated
 */
public interface StateMachine extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.cs130.statemachine.stateMachine.StateMachinePackage#getStateMachine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Vardefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vardefs</em>' containment reference.
   * @see #setVardefs(Variables)
   * @see org.xtext.cs130.statemachine.stateMachine.StateMachinePackage#getStateMachine_Vardefs()
   * @model containment="true"
   * @generated
   */
  Variables getVardefs();

  /**
   * Sets the value of the '{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getVardefs <em>Vardefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vardefs</em>' containment reference.
   * @see #getVardefs()
   * @generated
   */
  void setVardefs(Variables value);

  /**
   * Returns the value of the '<em><b>Eventdefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventdefs</em>' containment reference.
   * @see #setEventdefs(Events)
   * @see org.xtext.cs130.statemachine.stateMachine.StateMachinePackage#getStateMachine_Eventdefs()
   * @model containment="true"
   * @generated
   */
  Events getEventdefs();

  /**
   * Sets the value of the '{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getEventdefs <em>Eventdefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eventdefs</em>' containment reference.
   * @see #getEventdefs()
   * @generated
   */
  void setEventdefs(Events value);

  /**
   * Returns the value of the '<em><b>Statedefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statedefs</em>' containment reference.
   * @see #setStatedefs(States)
   * @see org.xtext.cs130.statemachine.stateMachine.StateMachinePackage#getStateMachine_Statedefs()
   * @model containment="true"
   * @generated
   */
  States getStatedefs();

  /**
   * Sets the value of the '{@link org.xtext.cs130.statemachine.stateMachine.StateMachine#getStatedefs <em>Statedefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statedefs</em>' containment reference.
   * @see #getStatedefs()
   * @generated
   */
  void setStatedefs(States value);

} // StateMachine
