/*
 * generated by Xtext 2.20.0
 */
package org.xtext.cs130.statemachine.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class StateMachineScopeProvider extends AbstractStateMachineScopeProvider {

}
